services:
  des-frontend:
    container_name: des-frontend
    build:
      context: ./app/frontend
      dockerfile: ./docker/frontend.Dockerfile
    env_file:
      - ./env/.env.frontend

  des-backend:
    container_name: des-backend
    build:
      context: ./app/backend/.
      dockerfile: ../../docker/backend.Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./env/.env.backend
